apiVersion: v1
kind: Pod
metadata:
  name: docker-pyspark
  labels:
    app: docker-pyspark
spec:
  containers:
  - image:  keithleosmith/docker-pyspark:2.4.5
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: spark-hwc
  restartPolicy: AlwaysTry run uisng --master local